apiVersion: batch/v1
kind: Job
metadata:
  name: "${JOB_NAME}"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "512m"
        sidecar.istio.io/proxyCPULimit: "1024m"
        sidecar.istio.io/proxyMemory: "512Mi"
        sidecar.istio.io/proxyMemoryLimit: "1024Mi"
    spec:
      serviceAccountName: etudelib
      restartPolicy: Never
      containers:
        - name: "${JOB_NAME}"
          image: "eu.gcr.io/${PROJECT_ID}/etude-loadgen:latest"
          resources:
            limits:
              cpu: "4"
              memory: "10Gi"
            requests:
              cpu: "4"
              memory: "10Gi"
          env:
            - name: VERTEX_ENDPOINT
              value: "${VERTEX_ENDPOINT}"
            - name: CATALOG_SIZE
              value: "${CATALOG_SIZE}"
            - name: JOURNEY_SOURCE
              value: "${JOURNEY_SOURCE}"
            - name: REPORT_LOCATION
              value: "${REPORT_LOCATION}"
            - name: TARGET_RPS
              value: "${TARGET_RPS}"
            - name: RAMP_DURATION_MINUTES
              value: "${RAMP_DURATION_MINUTES}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: "RuntimeDefault"




