apiVersion: batch/v1
kind: Job
metadata:
  name: etudelibtraining
  labels:
    app: etudelibtraining
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "512m"
        sidecar.istio.io/proxyCPULimit: "1024m"
        sidecar.istio.io/proxyMemory: "512Mi"
        sidecar.istio.io/proxyMemoryLimit: "1024Mi"
    spec:
      serviceAccountName: etudelib
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      restartPolicy: Never
      containers:
      - name: etudelib-training
        image: eu.gcr.io/${PROJECT_ID}/etudelib/serving_modeltraining:latest
        # command: [ "python3" ]
        # args: [ "train.py", "${PROJECT_ID}" ]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 600; done;" ]
        resources:
          requests:
            memory: "52Gi"
            cpu: 8
            ephemeral-storage: "20Gi"
          limits:
            nvidia.com/gpu: 1
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: "RuntimeDefault"
