apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVING_NAME}
  labels:
    app: ${SERVING_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVING_NAME}
  template:
    metadata:
      labels:
        app: ${SERVING_NAME}
    spec:
      serviceAccountName: etudelib
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - name: etudelib-servingrust
        image: eu.gcr.io/${PROJECT_ID}/etudelib/serving_rust:latest
#        command: [ "/bin/bash", "-c", "--" ]
#        args: [ "while true; do sleep 600; done;" ]
        command: [ "./start.sh" ]
        args: [ "${MODEL_PATH}", "${PAYLOAD_PATH}" ]
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 300   # Wait xx seconds before starting checks
          periodSeconds: 30          # Check every xx seconds
          timeoutSeconds: 5          # Wait up to 5 seconds for a response
          successThreshold: 1        # Consider ready after 1 successful check
          failureThreshold: 25        # Allow up to xxx consecutive failures before considering not ready. Init takes between 5 and 15 minutes
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Gi"
            cpu: 4
            ephemeral-storage: "20Gi"
          limits:
            nvidia.com/gpu: 1

