model:
  name: SINE
  layer_norm_eps: 1e-12
  prototype_size: 50
  interest_size: 3
  embedding_size: 64
  tau_ratio: 0.1
  reg_loss_ratio: 0.5

optimizer:
  lr: 0.02

trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">