---
apiVersion: v1
kind: Pod
metadata:
  name: etude-load-generator
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 1002
    runAsNonRoot: True
  serviceAccountName: "reco-analytics"
  containers:
    - name: etude-load-generator
      image: eu.gcr.io/bolcom-pro-reco-analytics-fcc/etude-load-generator:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 2000m
          memory: 3G
        requests:
          cpu: 1000m
          memory: 2G
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: '-XX:InitialRAMPercentage=70.0 -XX:MinRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0'

