apiVersion: batch/v1
kind: Job
metadata:
  name: "etude-loadtest-${LOADTEST_NAME}"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: reco-analytics
      restartPolicy: Never
      containers:
        - name: "etude-loadtest-${LOADTEST_NAME}"
          image: "eu.gcr.io/bolcom-pro-reco-analytics-fcc/etude-loadgen"
#          env:
#            - name: CATALOG_SIZE
#              value: "100"
#            - name: VERTX_ENDPOINT
#              value: ""
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: "RuntimeDefault"



