apiVersion: batch/v1
kind: Job
metadata:
  name: "${JOB_NAME}"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: reco-analytics
      restartPolicy: Never
      containers:
        - name: "${JOB_NAME}"
          image: "eu.gcr.io/bolcom-pro-reco-analytics-fcc/etude-loadgen:latest"
          env:
            - name: VERTEX_ENDPOINT
              value: "${VERTEX_ENDPOINT}"
            - name: CATALOG_SIZE
              value: "${CATALOG_SIZE}"
            - name: REPORT_LOCATION
              value: "${REPORT_URI}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: "RuntimeDefault"




