apiVersion: batch/v1
kind: Job
metadata:
  name: vertex-create-endpoint-${VERTEX_ENDPOINT}
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: reco-analytics
      restartPolicy: Never
      containers:
        - name: vertex-create-endpoint-${VERTEX_ENDPOINT}
          image: "eu.gcr.io/bolcom-stg-pyxle-images-043/vertexai-utilities:latest"
          args: [
            "--environment", "pro",
            "--project", "bolcom-pro-reco-analytics-fcc",
            "endpoints",
            "create",
            "--display-name", "${VERTEX_ENDPOINT}",
            "--description", "${VERTEX_ENDPOINT}",
          ]
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1001
