apiVersion: batch/v1
kind: Job
metadata:
  name: "${JOB_NAME}"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: reco-analytics
      restartPolicy: Never
      containers:
        - name: "${JOB_NAME}"
          image: "eu.gcr.io/bolcom-stg-pyxle-images-043/vertexai-utilities:latest"
          args: [
            "--project", "bolcom-pro-reco-analytics-fcc",
            "endpoints",
            "undeploy",
            "--endpoint",  "${VERTX_ENDPOINT_NAME_OR_ID}",
            "--model-id", "${VERTX_MODEL_ID}"
          ]
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true


