model:
  name: LightSANs
  n_layers: 2
  n_heads: 2
  k_interests: 15
  hidden_size: 64
  inner_size: 256
  hidden_dropout_prob: 0.5
  attn_dropout_prob: 0.5
  hidden_act: gelu
  layer_norm_eps: 1e-12
  initializer_range: 0.02
  topk: 21

optimizer:
  lr: 0.02

trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">