[package]
name = "rustloadtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goose = "^0.17"
goose-eggs = "0.5.1"
tokio = "^1.28.0"
serde_json = "1.0.96"
rand = "0.8.5"
