model:
  name: SASRec
  n_layers: 2
  n_heads: 2
  hidden_size: 64
  inner_size: 256
  hidden_dropout_prob: 0.5
  attn_dropout_prob: 0.5
  hidden_act: 'gelu'
  layer_norm_eps: 1e-12
  initializer_range: 0.02

optimizer:
  lr: 0.02

trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">