model:
  class_path: etudelib.models.lightsans
  init_args:
    input_size: [ 224, 224 ]
    backbone: wide_resnet50_2
    gamma_c: 1
    gamma_d: 1

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    n_layers: 2
    n_heads: 2
    k_interests: 15
    hidden_size: 64
    inner_size: 256
    hidden_dropout_prob: 0.5
    attn_dropout_prob: 0.5
    hidden_act: gelu
    layer_norm_eps: 1e-12
    initializer_range: 0.02
    seq_len: 50
    topk: 21


trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">