apiVersion: batch/v1
kind: Job
metadata:
  name: "${JOB_NAME}"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: reco-analytics
      restartPolicy: Never
      containers:
        - name: "${JOB_NAME}"
          image: "eu.gcr.io/bolcom-stg-pyxle-images-043/vertexai-utilities:latest"
          args: [
            "--environment", "pro",
            "--project",  "bolcom-pro-reco-analytics-fcc",
            "endpoints",
            "deploy",
            "--traffic-split", "0=100",
            "--undeploy-inactive",
            "--endpoint", "${VERTEX_ENDPOINT_NAME}",
            "--model", "${VERTEX_MODEL_NAME}",
            "--machine-type", "${VERTEX_MACHINE}",
            "--min-replica-count=1",
            "--max-replica-count=1",
            "--service-account", "reco-analytics",
          ]
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: "RuntimeDefault"



