apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudelibrust
  labels:
    app: etudelibrust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etudelibrust
  template:
    metadata:
      labels:
        app: etudelibrust
    spec:
      serviceAccountName: etudelib
      containers:
      - name: etudelib-servingrust
        image: eu.gcr.io/bk47478/etudelib/serving_rust:latest
        # args: ["gs://bk47478-shared/model_store/static/model.mar"]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 600; done;" ]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Gi"
            cpu: 6
            ephemeral-storage: "20Gi"

