apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudelibrust
  labels:
    app: etudelibrust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etudelibrust
  template:
    metadata:
      labels:
        app: etudelibrust
    spec:
      serviceAccountName: etudelib
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - name: etudelib-servingrust
        image: eu.gcr.io/bk47471/etudelib/serving_rust:latest
        command: [ "./start.sh" ]
        args: [ "gs://bk47471-shared/model_store/gru4rec_bolcom_t50_10000/gru4rec_bolcom_c10000_t50_jitopt.pth", "gs://bk47471-shared/model_store/gru4rec_bolcom_t50_10000/gru4rec_bolcom_c10000_t50_payload.yaml" ]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Gi"
            cpu: 4
            ephemeral-storage: "20Gi"
          limits:
            nvidia.com/gpu: 1

