apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudelibrust
  labels:
    app: etudelibrust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etudelibrust
  template:
    metadata:
      labels:
        app: etudelibrust
    spec:
      serviceAccountName: etudelib
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - name: etudelib-servingrust
        image: eu.gcr.io/bk47471/etudelib/serving_rust:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 600; done;" ]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Gi"
            cpu: 4
            ephemeral-storage: "100Gi"
          limits:
            nvidia.com/gpu: 1

