apiVersion: batch/v1
kind: Job
metadata:
  name: "${JOB_NAME}"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: reco-analytics
      restartPolicy: Never
      containers:
        - name: "${JOB_NAME}"
          image: "eu.gcr.io/bolcom-stg-pyxle-images-043/vertexai-utilities:latest"
          args: [
            "--project", "bolcom-pro-reco-analytics-fcc",
            "models",
            "deploy",
            "--display-name", "${VERTEX_MODEL_NAME}",
            "--container-image-url", "${VERTEX_MODEL_IMAGE}",
            "--container-port", "7080",
            "--predict-route", "/predictions/model",
            "--health-check-route", "/ping",
            "--description", "${VERTEX_MODEL_NAME}",
            "--is-default",
          ]
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: "RuntimeDefault"

