apiVersion: batch/v1
kind: Job
metadata:
  name: vertex-link-endpoint-model
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: reco-analytics
      restartPolicy: Never
      containers:
        - name: vertex-link-endpoint-model
          image: "eu.gcr.io/bolcom-stg-pyxle-images-043/vertexai-utilities:latest"
          args: [
            "--environment", "pro",
            "--project",  "bolcom-pro-reco-analytics-fcc",
            "endpoints",
            "deploy",
            "--traffic-split", "0=100",
            "--undeploy-inactive",
            "--endpoint", "noop_cpu",
            "--model", "noop",
            "--machine-type", "n1-highmem-4",
            "--min-replica-count=1",
            "--max-replica-count=1",
            "--service-account", "reco-analytics",
          ]
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1001

