host: "0.0.0.0"
port: 7080
# model_store_path must be "model_store" for the docker image to work
model_store_path: "model_store"
model_filename: "noop_bolcom_c1000000_t50_jitopt.pth"
payload_filename: "noop_bolcom_c1000000_t50_payload.yaml"